name: Deploy Docker Application

on:
  push:
    branches:
      - main # Run the workflow on pushes to the 'main' branch

jobs:
  deploy:
    name: Build, Push, and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t nagagogulan/angularproject:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push nagagogulan/angularproject:latest

      # Step 5: Set up SSH for EC2 connection
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          echo "SSH setup completed."

      # Step 6: Deploy the Docker image to EC2
      - name: Deploy Docker Image to EC2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "Deploying Docker image to EC2..."
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << EOF
            echo "Connected to EC2"
            # Pull the Docker image from Docker Hub
            docker pull nagagogulan/angularproject:latest
            # Run the Docker container
            docker run -d --name app-container -p 80:80 nagagogulan/angularproject:latest
            echo "Deployment completed successfully."
          EOF
