name: Deploy Application

on:
  push:
    branches:
      - main # Run the workflow on pushes to the 'main' branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for EC2 connection
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          echo "SSH setup completed."

      # Step 3: Build the application
      - name: Build Application
        run: |
          echo "Building application..."
          mkdir -p dist
          echo "<html><body><h1>Deployed Successfully</h1></body></html>" > dist/index.html
          echo "Build completed."

      # Step 4: Deploy to EC2 instance
      - name: Deploy to EC2
        env:
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        run: |
          echo "Deploying application to EC2..."
          scp -o StrictHostKeyChecking=no -r dist/* $SSH_USERNAME@$SSH_HOST:$DEPLOY_DIR
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << EOF
            echo "Connected to EC2"
            sudo systemctl restart nginx
            echo "Deployment completed successfully."
          EOF
